// <auto-generated />
using System;
using Masny.DotNet.Crud.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Masny.DotNet.Crud.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Masny.DotNet.Crud.Models.ChildModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BoolVar")
                        .HasColumnType("bit");

                    b.Property<string>("CharVar")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("DateTimeVar")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateVar")
                        .HasColumnType("date");

                    b.Property<decimal>("DecimalVar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("DoubleVar")
                        .HasColumnType("float");

                    b.Property<int>("EnumType")
                        .HasColumnType("int");

                    b.Property<float>("FloatVar")
                        .HasColumnType("real");

                    b.Property<int?>("IntNullVar")
                        .HasColumnType("int");

                    b.Property<int>("IntVar")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("StringNullVar")
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)");

                    b.Property<string>("StringVar")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ChildModels", "dbo");
                });

            modelBuilder.Entity("Masny.DotNet.Crud.Models.ParentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StringVar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ParentModels", "simple");
                });

            modelBuilder.Entity("Masny.DotNet.Crud.Models.ChildModel", b =>
                {
                    b.HasOne("Masny.DotNet.Crud.Models.ParentModel", "ParentModel")
                        .WithMany("ChildModels")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentModel");
                });

            modelBuilder.Entity("Masny.DotNet.Crud.Models.ParentModel", b =>
                {
                    b.Navigation("ChildModels");
                });
#pragma warning restore 612, 618
        }
    }
}
